name: Comment Bot

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # RubyとBundlerのインストール
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Diffを取得
      - name: Fetch PR diff
        run: |
          curl -v -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o pr.diff ${{ github.event.pull_request.diff_url }}

      - name: Check PR diff content
        run: |
          cat pr.diff

      - name: Execute openai-api.rb
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: bundle exec ruby openai-api.rb > openai-api_output

      - name: Create comments
        run: |
          echo "=== OpenaiApi Output ===" > comments
          cat openai-api_output >> comments

      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.ASSISTANT_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./comments "${URL}"
