name: Comment Bot

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute fizzbuzz.rb
        run: ruby fizzbuzz.rb > fizzbuzz_output

      - name: Create comments
        run: |
          echo "=== FizzBuzz Output ===" > comments
          cat fizzbuzz_output >> comments

      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.ASSISTANT_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./comments "${URL}"
