name: Hello Bot

on:
  pull_request:
    types: [opened]

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Post Hello Message
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo, number } = context.issue;
            const issueComment = await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: 'Hello Github!'
            });
